"""Shared error/warning code constants for compute modules."""

INVALID_NOTIONAL: str = "INVALID_NOTIONAL"
MISSING_DESCRIPTION: str = "MISSING_DESCRIPTION"
MISSING_NOTIONAL: str = "MISSING_NOTIONAL"
NO_PRIOR_MONTH_MATCH: str = "NO_PRIOR_MONTH_MATCH"
NO_PRIOR_MATCH: str = "NO_PRIOR_MATCH"

__all__ = [
    "INVALID_NOTIONAL",
    "MISSING_DESCRIPTION",
    "MISSING_NOTIONAL",
    "NO_PRIOR_MONTH_MATCH",
    "NO_PRIOR_MATCH",
]
